CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "PaymentMethods" (
    "Id" text NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Description" character varying(300),
    CONSTRAINT "PK_PaymentMethods" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Email" character varying(150) NOT NULL,
    "Password" character varying(255) NOT NULL,
    "Phone" character varying(50),
    "Img" character varying(500),
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Addresses" (
    "Id" text NOT NULL,
    "Name" character varying(200) NOT NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Addresses_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Restaurants" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TradeName" character varying(150) NOT NULL,
    "Address" character varying(250) NOT NULL,
    "CategoryId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "OpeningTime" character varying(10) NOT NULL,
    "ClosingTime" character varying(10) NOT NULL,
    "Img" character varying(500) NOT NULL,
    "Rating" character varying(5) NOT NULL,
    "IsOpen" boolean NOT NULL,
    "DeliveryFee" numeric(10,2) NOT NULL,
    "DeliveryTime" character varying(50) NOT NULL,
    CONSTRAINT "PK_Restaurants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Restaurants_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Restaurants_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Coupons" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(50) NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Discount" numeric(10,2) NOT NULL,
    "IsPercentage" boolean NOT NULL,
    "ExpirationDate" character varying(10) NOT NULL,
    "Active" boolean NOT NULL,
    "Stock" integer,
    "RestaurantId" integer,
    "UserId" integer,
    CONSTRAINT "PK_Coupons" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Coupons_Restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurants" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Coupons_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Dishes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Price" numeric(10,2) NOT NULL,
    "Img" character varying(500) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "RestaurantId" integer NOT NULL,
    CONSTRAINT "PK_Dishes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Dishes_Restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurants" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Orders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Restaurant" character varying(150) NOT NULL,
    "Status" character varying(20) NOT NULL,
    "Date" character varying(10) NOT NULL,
    "Time" character varying(10) NOT NULL,
    "CouponCodeApplied" character varying(50),
    "CustomerId" integer NOT NULL,
    "PaymentMethodId" character varying(50) NOT NULL,
    "AddressId" character varying(100) NOT NULL,
    "Total" numeric(10,2) NOT NULL,
    "RestaurantId" integer NOT NULL,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_PaymentMethods_PaymentMethodId" FOREIGN KEY ("PaymentMethodId") REFERENCES "PaymentMethods" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_Restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurants" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Orders_Users_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ReservedCoupons" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CouponId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "ReservedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ReservedCoupons" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReservedCoupons_Coupons_CouponId" FOREIGN KEY ("CouponId") REFERENCES "Coupons" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReservedCoupons_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "OrderItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OrderId" integer NOT NULL,
    "DishId" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Name" character varying(150) NOT NULL,
    "Price" numeric(10,2) NOT NULL,
    CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderItems_Dishes_DishId" FOREIGN KEY ("DishId") REFERENCES "Dishes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Addresses_UserId" ON "Addresses" ("UserId");

CREATE INDEX "IX_Coupons_RestaurantId" ON "Coupons" ("RestaurantId");

CREATE INDEX "IX_Coupons_UserId" ON "Coupons" ("UserId");

CREATE INDEX "IX_Dishes_RestaurantId" ON "Dishes" ("RestaurantId");

CREATE INDEX "IX_OrderItems_DishId" ON "OrderItems" ("DishId");

CREATE INDEX "IX_OrderItems_OrderId" ON "OrderItems" ("OrderId");

CREATE INDEX "IX_Orders_AddressId" ON "Orders" ("AddressId");

CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");

CREATE INDEX "IX_Orders_PaymentMethodId" ON "Orders" ("PaymentMethodId");

CREATE INDEX "IX_Orders_RestaurantId" ON "Orders" ("RestaurantId");

CREATE INDEX "IX_ReservedCoupons_CouponId" ON "ReservedCoupons" ("CouponId");

CREATE INDEX "IX_ReservedCoupons_UserId" ON "ReservedCoupons" ("UserId");

CREATE INDEX "IX_Restaurants_CategoryId" ON "Restaurants" ("CategoryId");

CREATE INDEX "IX_Restaurants_UserId" ON "Restaurants" ("UserId");

CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260813082215_InitialPostgres', '10.0.4');

COMMIT;

